### ISSUE TITLE
Support for app-per-PR

### ISSUE THREAD

**Issue by bmann** [fission-suite/publish-action#8]
Right now, we can do a deploy on PR, but each PR clobbers the previous one, as just one app is used for all PR triggers.

Instead, for each PR, generate a new Fission app / subdomain -- can just use the standard `long-thin-fairy` subdomain generation -- and deploy the PR to that.

This gives every PR submitter a separate example app that is live to show.

**Comment by walkah** [comment]
this is how it works today.
